
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '17'

steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '$(javaVersion)'
      architecture: 'x64'
    displayName: 'Set up Java $(javaVersion)'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-Xmx1024m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
    displayName: 'Build and test with Maven'
