name: Testing configuration variables

on:
  workflow_dispatch:

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: [self-hosted, Linux, X64, label-1]

    env:
      Greeting: Hello

    steps:
      - name: "Say hello to vishal"
        run: echo "$Greeting $First_Name is using $cloud with project ${{ vars.PROJECT_ID }}"
        env:
          First_Name: Vishal
